const Map<String, dynamic> kFabricationDefaultJson = <String, dynamic>{
  'tank': <String, dynamic>{
    'tank_L': '',
    'tank_W': '',
    'tank_H': '',
    'tank_Thick': '',
    'tank_Bot_Thick': '',
    'tank_Flg_Thick': '',
  },
  'stiffner': <String, dynamic>{},
  'radiator': <String, dynamic>{
    'radiator_CC': '',
    'radiator_W': '',
    'radiator_Fin_Nos': '',
    'radiator_Nos': '',
    'radiator_Left_Nos': '',
    'radiator_Right_Nos': '',
    'radiator_Vlv': '',
  },
  'fill_Vlv': <String, dynamic>{'fill_Vlv': true, 'fill_Vlv_Nos': ''},
  'drain_Vlv': <String, dynamic>{'drain_Vlv': true, 'drain_Vlv_Nos': ''},
  'smpl_Vlv': <String, dynamic>{'smpl_Vlv': true, 'smpl_Vlv_Nos': ''},
  'tank_LiftLug': <String, dynamic>{},
  'jackpad': <String, dynamic>{},
  'hvb': <String, dynamic>{'hvb_Volt': '', 'hvb_Amp': '', 'hvb_Pos': 'lid'},
  'lvb': <String, dynamic>{'lvb_Volt': '', 'lvb_Amp': '', 'lvb_Pos': 'lid'},
  'hvcb': <String, dynamic>{'hvcb': false},
  'lvcb': <String, dynamic>{'lvcb': false},
  'lid': <String, dynamic>{'lid_Thick': ''},
  'cons': <String, dynamic>{'cons_Vol': '', 'cons_Dia': '', 'cons_L': ''},
  'buch_Rely': <String, dynamic>{},
  'gorPipe': <String, dynamic>{
    'buchholz_Relay': false,
    'single_Valve': true,
    'valve_Type1': true,
  },
  'mog': <String, dynamic>{'mog': false, 'mog_Tlt_Ang': ''},
  'exp_Vent': <String, dynamic>{
    'exp_Vent': true,
    'exp_Vent_ID': '',
    'exp_Vent_With_OI': false,
  },
  'inspect': <String, dynamic>{},
  'bot_Chnl': <String, dynamic>{'isRoller': false},
  'roller': <String, dynamic>{
    'roller': true,
    'roller_Type': '',
    'roller_Guage': '',
  },
  'cf': <String, dynamic>{},
  'lid_LiftLug': <String, dynamic>{
    'lid_LiftLug': true,
    'lid_LiftLug_Thick': '',
  },
  'thermoPkt': <String, dynamic>{'thermoPkt1': false, 'thermoPkt2': false},
  'restOfVariables': <String, dynamic>{
    'designId': '',
    'kVA': '',
    'transformer_Weight': '',
    'limb_CC': '',
    'limb_Nos': '',
    'limb_H': '',
    'eVectorGroup': '',
    'prv': '',
    'mbox': '',
    'mbox_Inst_Nos': '',
    'thrmo_Syphn': '',
  },
  'fabricationCore': <String, dynamic>{'core_Dia': ''},
  'coreFoot': <String, dynamic>{},
  'lift_Cons': <String, dynamic>{},
  'hv': <String, dynamic>{'hv_ID': '', 'hv_OD': '', 'hv_Wdg_L': ''},
  'lv': <String, dynamic>{
    'lv_ID': '',
    'lv_OD': '',
    'lv_Wdg_L': '',
    'lv_Volts': '',
  },
  'hvct': <String, dynamic>{},
  'lvct': <String, dynamic>{},
  'octcFlange': <String, dynamic>{'isoctc': false},
  'printOuts': <String, dynamic>{},
  'turnsPerTap': '',
  'tapVoltages': '',
  'tapCurrent': '',
  'tapStepPercentage': '',
};
