import 'lom_material_draft.dart';

const List<LomMaterialDraft> kLomCostDefaults = <LomMaterialDraft>[
  LomMaterialDraft(materialName: 'Lamination', materialRate: 220.0),
  LomMaterialDraft(materialName: 'HV Conductor', materialRate: 125.0),
  LomMaterialDraft(materialName: 'LV Conductor', materialRate: 125.0),
  LomMaterialDraft(materialName: 'HV Connection Leads', materialRate: 520.0),
  LomMaterialDraft(materialName: 'LV Connection Leads', materialRate: 520.0),
  LomMaterialDraft(materialName: 'Insulation Material', materialRate: 120.0),
  LomMaterialDraft(materialName: 'Transformer Oil', materialRate: 65.0),
  LomMaterialDraft(materialName: 'Tank, Lid, etc.', materialRate: 32.0),
  LomMaterialDraft(materialName: 'Cable Box, HV', materialRate: 7000.0),
  LomMaterialDraft(materialName: 'Cable Box, LV', materialRate: 3000.0),
  LomMaterialDraft(materialName: 'Bushing, HV', materialRate: 3000.0),
  LomMaterialDraft(materialName: 'Bushing, LV', materialRate: 3000.0),
  LomMaterialDraft(materialName: 'Radiator/ Heat Exch', materialRate: 150.0),
  LomMaterialDraft(materialName: 'Perma Wood Items', materialRate: 150.0),
  LomMaterialDraft(materialName: 'Drain Valve', materialRate: 3000.0),
  LomMaterialDraft(materialName: 'Filter Valve', materialRate: 3000.0),
  LomMaterialDraft(materialName: 'Sampling Valve', materialRate: 1000.0),
  LomMaterialDraft(materialName: 'Relay Shut-off Valve', materialRate: 3000.0),
  LomMaterialDraft(materialName: 'Breather Si Gel', materialRate: 500.0),
  LomMaterialDraft(materialName: 'Rating Plate', materialRate: 1000.0),
  LomMaterialDraft(materialName: 'Thermometer Pocket', materialRate: 75.0),
  LomMaterialDraft(materialName: 'Air Release Plug', materialRate: 75.0),
  LomMaterialDraft(materialName: 'Core bolts and tie rods', materialRate: 35.0),
  LomMaterialDraft(materialName: 'OLTC', materialRate: 350000.0),
  LomMaterialDraft(materialName: 'OCTC', materialRate: 20000.0),
  LomMaterialDraft(materialName: 'OTI', materialRate: 3000.0),
  LomMaterialDraft(materialName: 'WTI and WTICT', materialRate: 5000.0),
  LomMaterialDraft(materialName: 'Buchholz Relay', materialRate: 5000.0),
  LomMaterialDraft(materialName: 'Marshalling Box', materialRate: 10000.0),
  LomMaterialDraft(materialName: 'Oil Level gauge', materialRate: 750.0),
  LomMaterialDraft(materialName: 'MOG', materialRate: 5000.0),
  LomMaterialDraft(materialName: 'Pressure Relief Valve', materialRate: 5000.0),
  LomMaterialDraft(materialName: 'Oil Circulating Pump', materialRate: 25000.0),
  LomMaterialDraft(materialName: 'AVR and RTCC Panel', materialRate: 100000.0),
  LomMaterialDraft(materialName: 'CI Rollers Assembly', materialRate: 200.0),
  LomMaterialDraft(materialName: 'Pump Control Cubicle', materialRate: 45000.0),
  LomMaterialDraft(materialName: 'Bi-metallic Connector', materialRate: 800.0),
  LomMaterialDraft(materialName: 'Fasteners', materialRate: 42.0),
];
