const Map<String, Object?> kTwoWindingDefaultJson = <String, Object?>{
  'designId': '',
  'eTransBodyType': 'CIRCULAR',
  'eTransCostType': 'ECONOMIC',
  'kVA': '',
  'lowVoltage': 433,
  'highVoltage': 11000,
  'lVConductorMaterial': 'Cu',
  'hVConductorMaterial': 'Cu',
  'lvCurrentDensity': '4.24',
  'hvCurrentDensity': '4.24',
  'lvWindingType': 'HELICAL',
  'hvWindingType': 'HELICAL',
  'lVLimbs': 'Series',
  'hVLimbs': 'Series',
  'frequency': '50',
  'vectorGroup': 'Dyn11',
  'buildFactor': 1.3,
  'voltsPerTurn': 0,
  'kValue': 0,
  'fluxDensity': '',
  'tapStepsPercent': '',
  'tapStepsPositive': '',
  'tapStepsNegative': '',
  'limitW': '',
  'tankLoss': '',
  'loadLoss': '',
  'coreLoss': '',
  'limitEz': '',
  'isOLTC': false,
  'isCSP': false,
  'ez': '',
  'hvImpulseVoltage': '',
  'hvTestVoltage': '',
  'lvImpulseVoltage': '',
  'lvTestVoltage': '',
  'lossesAt50Percent': '',
  'lossesAt100Percent': '',
  'core': <String, Object?>{
    'coreType': 'PRIME',
    'coreDia': '',
    'limbHt': '',
    'cenDist': '',
    'area': '',
    'blade': '',
    'fluxDensity': '',
    'wkgGrade': '',
    'coreWeight': '',
    'coreMaterial': 'NipM4',
  },
  'commonFormulas': <String, Object?>{'er': '', 'ex': '', 'ek': ''},
  'tank': <String, Object?>{
    'tankLength': '',
    'tankWidth': '',
    'tankHeight': '',
    'tankCapacity': '',
    'tankLoss': '',
    'wdgToTankGap': '',
    'connectionGap': '',
    'topYokeToCoverGap': '',
  },
  'innerWindings': <String, Object?>{
    'turnsPerPhase': '',
    'phaseCurrent': '',
    'currentDensity': '',
    'condCrossSec': '',
    'conductorSizes': '',
    'condInsulation': '',
    'noInParallel': '',
    'windingLength': '',
    'noOfLayers': '',
    'turnsLayers': '',
    'interLayerInsulation': '',
    'noOfDuctsWidth': '',
    'ducts': '',
    'ductSize': '',
    'discDuctSize': '',
    'terminal': '',
    'endClearances': '',
    'eddyStrayLoss': '',
    'tempGradDegC': '',
    'weightBareInsulated': '',
    'loadLoss': '',
    'commRawCond': '',
    'radialParallelCond': '',
    'axialParallelCond': '',
    'condBreadth': '',
    'condHeight': '',
    'conductorDiameter': '',
    'isConductorRound': '',
    'isEnamel': false,
  },
  'outerWindings': <String, Object?>{
    'turnsPerPhase': '',
    'phaseCurrent': '',
    'currentDensity': '',
    'condCrossSec': '',
    'conductorSizes': '',
    'condInsulation': '',
    'noInParallel': '',
    'windingLength': '',
    'noOfLayers': '',
    'turnsLayers': '',
    'interLayerInsulation': '',
    'noOfDuctsWidth': '',
    'ducts': '',
    'ductSize': '',
    'discDuctSize': '',
    'terminal': '',
    'endClearances': '',
    'eddyStrayLoss': '',
    'tempGradDegC': '',
    'weightBareInsulated': '',
    'loadLoss': '',
    'commRawCond': '',
    'radialParallelCond': '',
    'axialParallelCond': '',
    'condBreadth': '',
    'condHeight': '',
    'conductorDiameter': '',
    'isConductorRound': '',
    'isEnamel': false,
  },
  'coilDimensions': <String, Object?>{
    'coreDia': '',
    'coreGap': '',
    'activePartSize': '',
    'lvid': '',
    'lvradial': '',
    'lvod': '',
    'lvhvgap': '',
    'hvid': '',
    'hvradial': '',
    'hvod': '',
    'hvhvgap': '',
  },
  'preview': '',
  'coreLVClr': '',
  'lVHVClr': '',
  'hVHVGap': '',
  'oilDucts': '',
  'lvNoWidth': '',
  'hvNoWidth': '',
  'lVLayerInsulation': '',
  'hVLayerInsulation': '',
  'buildFact': '',
  'coreWtKg': '',
  'cuWtKg': '',
  'coilDimensionsGeneralInfoCostings': '',
  'coilWindingDimensionsInMm': '',
  'lvFormulas': <String, Object?>{
    'possibleCoreDiaRange': '',
    'possibleWindowHeightRange': '',
    'lvConnectionWeight': '',
    'lvProcurementWeight': '',
    'lvCurrentPerPhase': '',
    'lvWidthOfSpacer': '',
    'lvNoOfSpacers': '',
    'lvTransposition': '',
  },
  'hvFormulas': <String, Object?>{
    'centerDistance': '',
    'hvNoOfSpacers': '',
    'hvNoOfCoils': '',
    'hvConnectionWeight': '',
    'hvRadialThickness': '',
    'hvWidthOfSpacer': '',
    'hvIsEnamel': false,
    'hvWdgLengthPerCoil': '',
    'hvR75': '',
    'coreWeight': '',
    'hvCurrentPerPhase': '',
    'hvHeightInsulated': '',
    'hvGapBwCoil': '',
    'hvDuctThickness': '',
    'totalLoadLoss': '',
    'hvTransposition': '',
    'hvVoltsPerPhase': '',
    'hvRadialParallelConductors': '',
    'tapVoltages': <Object?>[],
    'hvTurnsPerPhase': '',
    'hvEndClearance': '',
    'hvConductorDia': '',
    'rW': '',
    'hvTurnsPerTap': '',
    'hvAxialParallelConductors': '',
    'hvInterLayerInsulation': '',
    'tankLoss': '',
    'hvNoOfDiscs': '',
    'hvOd': '',
    'activePartSize': '',
    'hvTurnsAtHighest': '',
    'hvTurnsPerLayer': '',
    'hvDiscDuctsSize': '',
    'hvLoadLossAtNormal': '',
    'hvConductorCrossSection': '',
    'hvR26': '',
    'hvStrayLoss': '',
    'hvTurnsAtLowest': '',
    'hvCurrentAtLowest': '',
    'hvBareWeight': '',
    'hVRevisedCurrDenAtLowest': '',
    'hvRevisedCondCrossSection': '',
    'hvTurnsPerCoil': '',
    'hvConductorInsulation': '',
    'coreLength': '',
    'hvBreadth': '',
    'coreLoss': '',
    'psi': '',
    'tapCurrent': <Object?>[],
    'hvGradient': '',
    'hVRevisedCurrDenAtNormal': '',
    'specificLossBeyondLimits': false,
    'hvNoOfDoubleDiscs': '',
    'hvWireLength': '',
    'specificLoss': '',
    'lvHvGap': '',
    'hvLmt': '',
    'hvNoOfDuct': '',
    'hvDiscArrangement': '',
    'turnsPerTap': <Object?>[],
    'kW55': '',
    'hvHeight': '',
    'hvLoadLossAtLowest': '',
    'hvBreadthInsulated': '',
    'hvNumberOfLayers': '',
    'hvHvGap': '',
    'hvTotalCondCrossSection': '',
    'hvWindingLength': '',
    'hvNoOfConductors': '',
    'hvXOverTurnsLayers': '',
    'hvProcurementWeight': '',
    'hvInsulatedWeight': '',
    'hvId': '',
    'v0': '',
    'hvIsConductorRound': false,
  },
  'tankAndOilFormulas': <String, Object?>{
    'coolingStatement': 'Details can be displayed',
    'conservatorDia': '',
    'conservatorLength': '',
    'wdgTankGap': '',
    'connectionGap': '',
    'topYokeCoverGap': '',
    'totalConductorWeight': '',
    'totalSteelWeight': '',
    'totalOil': '',
    'insulationWeight': '',
    'totalRadiatorWeight': '',
    'weightOfTankAndAcc': '',
    'tankDimension': '',
    'overallDimension': '',
    'radiatorWidth': 226,
  },
  'eRadiatorType': 'RADIATOR',
  'turnsPerTap': '',
  'ambientTemp': '',
  'windingTemp': '',
  'topOilTemp': '50',
  'dryType': false,
  'dryTempClass': '',
  'radiatorWidth': 226,
  'cost': <String, Object?>{
    'copperCostPerKg': '',
    'aluminiumCostPerKg': '',
    'coreCostPerKg': '',
    'steelCostPerKg': '',
    'oilCostPerKg': '',
    'insulationCostPerKg': '',
    'radiatorCostPerKg': '',
    'totalCondCost': '',
    'totalCoreCost': '',
    'totalSteelCost': '',
    'totalOilCost': '',
    'totalInsCost': '',
    'totalRadiatorCost': '',
    'capitalCost': '',
  },
  'lockedAttributes': <String, Object?>{
    'coreLock': <String, Object?>{'coreDia': false, 'limbHt': false},
    'innerWindings': <String, Object?>{
      'turnsPerPhase': false,
      'conductorSizes': false,
      'noInParallel': false,
      'condBreadth': false,
      'condHeight': false,
    },
    'outerWindings': <String, Object?>{
      'turnsPerPhase': false,
      'conductorSizes': false,
      'noInParallel': false,
      'condBreadth': false,
      'condHeight': false,
    },
  },
  'comments': <String, Object?>{
    'tapStepComment': '',
    'wattPerKgComment': '',
    'lvCondInsComment': '',
    'hvCondInsComment': '',
    'lvInterLayerInsComment': '',
    'hvInterLayerInsComment': '',
    'lvDuctWidthComment': '',
    'hvDuctWidthComment': '',
    'lvEndClrComment': '',
    'hvEndClrComment': '',
    'coreToLvClrComment': '',
    'lvToHvClrComment': '',
    'hvToHvClrComment': '',
  },
};
